### ISSUE TITLE
Add in site logo

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/mavc-theme#10]
We need to get a logo for the website (as in the site name logo) from Carter and the iLab team: @paullenz can you discuss this with them on your wind down on Saturday?

**Comment by JenMysoc** [comment]
It's likely this will come in at the end of next week so could be moved to the next sprint!

**Comment by Gemmamysoc** [comment]
![infoliblogo1](https://cloud.githubusercontent.com/assets/6806067/9633662/e3f2b970-5185-11e5-8b7e-0bde82e5b982.png)

**Comment by Gemmamysoc** [comment]
Info from Carter 2 Sept:

## Header:
- [x] The Logo should be placed at the left of the header while the flag be moved to the far right of the header. 
- [x] It should be rotated so the star faces the far corner in the header, with its tail fading in the same manner. 
- [ ] Please brighten the flag a bit so it shows up distinctly rather than the fading throughout.

**Comment by wrightmartin** [comment]
> Please brighten the flag a bit so it shows up distinctly rather than the fading throughout.

This isn't possible - the log in links, and then, once you're logged in the account management links appear there, you won't be able to read them if the flag is opaque here. (see WDTK screenshot)

![screen shot 2015-09-14 at 16 20 33](https://cloud.githubusercontent.com/assets/2292925/9853647/8fed4c0c-5afc-11e5-8a3b-f3431ddabf1b.png)
